<?php

use Drupal\Core\Render\Markup;

function ucsc_mailer_cron() {
  require_once("ucsc_mailer_send.php");
	ucsc_mailer_send();
}

/**
* Implements hook_mail(). Notes on configuration of mail. Must use Swift Mailer.
 * Set '/admin/config/system/mailsystem' to Formatter: Swift Mailer, Sender:
 * Swift Mailer, Theme: BSOE Plain.
 * Set 'admin/config/swiftmailer/transport' - Transport tab: Transport Types: PHP
 * Messages tab: Message Format: HTML, Plain Text Version: Yes (Generate checked),
 * Character set: UTF-8
*/

function ucsc_mailer_mail($key, &$message, $params) {
  $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';	
  switch ($key) {
    case 'mailer_create_submission':
      $message['subject'] = t('BSOE Mailer Submission: @title',
        array('@title' => $params['node_title'])) . " created on: " . date("m-d-Y h:i");
      $message['field_mailer_body'][] = $params['field_mailer_body'];
      break;
   
    /*case 'mailer_weekly':
      $message['subject'] = 'BSOE Undergraduate Mailer for ' . date("m/d/Y");
      $message['field_mailer_body'][] = $params['message'];
      break;
     */
 }
}

/**
* Implements hook_entity_insert().
*/
function ucsc_mailer_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {

  // Restrict to entities that need a notification
  if ($entity->bundle() === 'mailer') {

    $mailManager = \Drupal::service('plugin.manager.mail');
    $module = 'ucsc_mailer';
    $key = 'mailer_create_submission';
    $to = $entity->get('field_mailer_recipient')->value;
    $langcode = \Drupal::currentUser()->getPreferredLangcode();

    // Creating the params for this message.
    // Get information from this entity.
    $params['node_title'] = $entity->label();

    // Use those to create the message. We add inline styles so that it shows up
    // in the email.
    $field_mailer_body = Markup::create($entity->get('field_mailer_body')->value);

    //$link = $entity->toUrl()->toString();
    $params['field_mailer_body'] = Markup::create($field_mailer_body);

    $from = $entity->get('field_mailer_sender_address');
    $send = true;
    $result = $mailManager->mail($module, $key, $to, $langcode, $params, $from, $send);

    // Notify of the result.
    if ($result['result'] !== true) {
      drupal_set_message(t('There was a problem sending your message and it was not sent.'), 'error');
    }
    else {
      drupal_set_message(t('Your message has been sent.'));
    }
  } else {
    return;
  }
}
